In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.preprocessing import LabelEncoder, StandardScaler
label = LabelEncoder()
Ss = StandardScaler()
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import f1_score


import warnings
warnings.filterwarnings('ignore')

In [2]:
train = pd.read_csv('training_.csv')
test = pd.read_csv('test.csv')

In [3]:
train.shape, test.shape

((1048, 28), (210, 27))

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   S.No                       1048 non-null   int64
 1   Timestamp                  1048 non-null   object
 2   Age                        1048 non-null   int64
 3   Gender                     1048 non-null   object
 4   Country                    1048 non-null   object
 5   state                      636 non-null    object
 6   self_employed              1030 non-null   object
 7   family_history             1048 non-null   object
 8   treatment                  1048 non-null   object
 9   work_interfere             812 non-null    object
 10  no_employees               1048 non-null   object
 11  remote_work                1048 non-null   object
 12  tech_company               1048 non-null   object
 13  benefits                   1048 non-null   object
 14  care_options               1048 non-null   object
 15  wellness_program           1048 non-null   object
 16  seek_help                  1048 non-null   object
 17  anonymity                  1048 non-null   object
 18  leave                      1048 non-null   object
 19  mental_health_consequence  1048 non-null   object
 20  phys_health_consequence    1048 non-null   object
 21  coworkers                  1048 non-null   object
 22  supervisor                 1048 non-null   object
 23  mental_health_interview    1048 non-null   object
 24  phys_health_interview      1048 non-null   object
 25  mental_vs_physical         1048 non-null   object
 26  obs_consequence            1048 non-null   object
 27  comments                   132 non-null    object
dtypes: int64(2), object(26)
memory usage: 229.4+ KB

In [5]:
train.describe(include = 'all')

,S.No,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
count,1048.000000,1048,1.048000e+03,1048,1048,636,1030,1048,1048,812,...,1048,1048,1048,1048,1048,1048,1048,1048,1048,132
unique,NaN,1035,NaN,45,42,45,2,2,2,4,...,5,3,3,3,3,3,3,3,2,128
top,NaN,2014-08-28 16:58:33,NaN,Male,United States,CA,No,No,No,Sometimes,...,Don't know,No,No,Some of them,Yes,No,Maybe,Don't know,No,* Small family business - YMMV.
freq,NaN,2,NaN,518,644,123,906,643,536,386,...,466,424,773,651,439,835,461,471,902,5
mean,524.500000,NaN,9.541988e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,302.675844,NaN,3.089010e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,-1.726000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,262.750000,NaN,2.700000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,524.500000,NaN,3.100000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,786.250000,NaN,3.600000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1048.000000,NaN,1.000000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   S.No                       210 non-null    int64
 1   Timestamp                  210 non-null    object
 2   Age                        210 non-null    int64
 3   Gender                     210 non-null    object
 4   Country                    210 non-null    object
 5   state                      107 non-null    object
 6   self_employed              210 non-null    object
 7   family_history             210 non-null    object
 8   work_interfere             182 non-null    object
 9   no_employees               210 non-null    object
 10  remote_work                210 non-null    object
 11  tech_company               210 non-null    object
 12  benefits                   210 non-null    object
 13  care_options               210 non-null    object
 14  wellness_program           210 non-null    object
 15  seek_help                  210 non-null    object
 16  anonymity                  210 non-null    object
 17  leave                      210 non-null    object
 18  mental_health_consequence  210 non-null    object
 19  phys_health_consequence    210 non-null    object
 20  coworkers                  210 non-null    object
 21  supervisor                 210 non-null    object
 22  mental_health_interview    210 non-null    object
 23  phys_health_interview      210 non-null    object
 24  mental_vs_physical         210 non-null    object
 25  obs_consequence            210 non-null    object
 26  comments                   32 non-null     object
dtypes: int64(2), object(25)
memory usage: 44.4+ KB

In [7]:
test.describe(include = 'all')

,S.No,Timestamp,Age,Gender,Country,state,self_employed,family_history,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
count,210.000000,210,210.000000,210,210,107,210,210,182,210,...,210,210,210,210,210,210,210,210,210,32
unique,NaN,210,NaN,14,29,23,2,2,4,6,...,5,3,3,3,3,3,3,3,2,32
top,NaN,2014-08-29 17:04:12,NaN,Male,United States,CA,No,No,Sometimes,More than 1000,...,Don't know,Maybe,No,Some of them,Yes,No,Maybe,Don't know,No,These result may be a tad confusing so a summa...
freq,NaN,1,NaN,96,106,15,189,123,79,55,...,97,97,151,122,77,172,96,105,173,1
mean,105.500000,NaN,32.547619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,60.765944,NaN,8.061968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,53.250000,NaN,27.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,105.500000,NaN,32.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,157.750000,NaN,37.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,210.000000,NaN,72.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Data Mining/Cleaning

In [8]:
test.isna().sum()

S.No                           0
Timestamp                      0
Age                            0
Gender                         0
Country                        0
state                        103
self_employed                  0
family_history                 0
work_interfere                28
no_employees                   0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
leave                          0
mental_health_consequence      0
phys_health_consequence        0
coworkers                      0
supervisor                     0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
comments                     178
dtype: int64

In [9]:
train.isna().sum()

S.No                           0
Timestamp                      0
Age                            0
Gender                         0
Country                        0
state                        412
self_employed                 18
family_history                 0
treatment                      0
work_interfere               236
no_employees                   0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
leave                          0
mental_health_consequence      0
phys_health_consequence        0
coworkers                      0
supervisor                     0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
comments                     916
dtype: int64

After looking into the dataset here are the things that i noticed:

1. Amoung 28 columns in training dataset 25 are of 'object' datatype and 2 are int64 
   and Timestamp is object which need is to be converted to datetime_dtype.
2. state column has 412 missing values in Training Dataset and 103 in Testing.
3. work_interfere column has 236 missing values in Training Dataset and 28 in Testing.
4. self_employed column has 18 missing values in Training Dataset.
5. comments column has 916 missing values in Training Dataset and 178 in Testing.

MY Views:

1. Drop comments columm from Training and Testing datasets as almost 90% of data is missing.
   so it cannot be considered as Important feature for predicting the Outcome.
2. since state and work_interfere columns are object datatypes they are to be filled with mode.
3. object columns are to be converted using LabelEncoder for predicting the Outcome.

In [10]:
#drop comments column
Train = train.drop(['comments','Timestamp'], axis = 1)
Test = test.drop(['comments','Timestamp'], axis = 1)

In [11]:
#filling values of missing columns with mode()[0]

#State column
Train['state'] = Train['state'].fillna(Train['state'].mode()[0])
Test['state'] = Test['state'].fillna(Test['state'].mode()[0])

#self_employed column
Train['self_employed'] = Train['self_employed'].fillna(Train['self_employed'].mode()[0])

#work_interfere column
Train['work_interfere'] = Train['work_interfere'].fillna(Train['work_interfere'].mode()[0])
Test['work_interfere'] = Test['work_interfere'].fillna(Test['work_interfere'].mode()[0])

In [12]:
#rechecking for null/missing values
Train.isna().sum()

S.No                         0
Age                          0
Gender                       0
Country                      0
state                        0
self_employed                0
family_history               0
treatment                    0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

In [13]:
Test.isna().sum()

S.No                         0
Age                          0
Gender                       0
Country                      0
state                        0
self_employed                0
family_history               0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

# Data Preprocessing

In [14]:
Train.columns

Index(['S.No', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence'],
      dtype='object')

To get a higher score / productionalizing the model

All the imputation and interaction features would be made twice for the train set and test set.

In [15]:
Train1 = Train
Test1 = Test

In [16]:
cols = ['Country', 'state',
        'self_employed', 'family_history', 'work_interfere',
        'no_employees', 'remote_work', 'tech_company', 'benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['Gender '+str(i)] = Train['Gender'].astype(str)+'_'+Train[i].astype(str)
    Test1['Gender '+str(i)] = Test['Gender'].astype(str)+'_'+Test[i].astype(str)

In [17]:
cols = ['self_employed', 'family_history', 'work_interfere',
        'no_employees', 'remote_work', 'tech_company', 'benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['state '+str(i)] = Train['state'].astype(str)+'_'+Train[i].astype(str)
    Test1['state '+str(i)] = Test['state'].astype(str)+'_'+Test[i].astype(str)

In [18]:
cols = ['family_history', 'work_interfere',
        'no_employees', 'remote_work', 'tech_company', 'benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['self_employed '+str(i)] = Train['self_employed'].astype(str)+'_'+Train[i].astype(str)
    Test1['self_employed '+str(i)] = Test['self_employed'].astype(str)+'_'+Test[i].astype(str)

In [19]:
cols = ['work_interfere',
        'no_employees', 'remote_work', 'tech_company', 'benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['family_history '+str(i)] = Train['family_history'].astype(str)+'_'+Train[i].astype(str)
    Test1['family_history '+str(i)] = Test['family_history'].astype(str)+'_'+Test[i].astype(str)

In [20]:
cols = ['no_employees', 'remote_work', 'tech_company', 'benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['work_interfere '+str(i)] = Train['work_interfere'].astype(str)+'_'+Train[i].astype(str)
    Test1['work_interfere'+str(i)] = Test['work_interfere'].astype(str)+'_'+Test[i].astype(str)

In [21]:
cols = ['remote_work', 'tech_company', 'benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['no_employees '+str(i)] = Train['no_employees'].astype(str)+'_'+Train[i].astype(str)
    Test1['no_employees'+str(i)] = Test['no_employees'].astype(str)+'_'+Test[i].astype(str)

In [22]:
cols = ['tech_company', 'benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['remote_work '+str(i)] = Train['remote_work'].astype(str)+'_'+Train[i].astype(str)
    Test1['remote_work'+str(i)] = Test['remote_work'].astype(str)+'_'+Test[i].astype(str)

In [23]:
cols = ['benefits',
        'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['tech_company '+str(i)] = Train['tech_company'].astype(str)+'_'+Train[i].astype(str)
    Test1['tech_company'+str(i)] = Test['tech_company'].astype(str)+'_'+Test[i].astype(str)

In [24]:
cols = ['care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['benefits '+str(i)] = Train['benefits'].astype(str)+'_'+Train[i].astype(str)
    Test1['benefits'+str(i)] = Test['benefits'].astype(str)+'_'+Test[i].astype(str)

In [25]:
cols = ['wellness_program', 'seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['care_options'+str(i)] = Train['care_options'].astype(str)+'_'+Train[i].astype(str)
    Test1['care_options'+str(i)] = Test['care_options'].astype(str)+'_'+Test[i].astype(str)

In [26]:
cols = ['seek_help', 'anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['wellness_program'+str(i)] = Train['wellness_program'].astype(str)+'_'+Train[i].astype(str)
    Test1['wellness_program'+str(i)] = Test['wellness_program'].astype(str)+'_'+Test[i].astype(str)

In [27]:
cols = ['anonymity', 'leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['seek_help'+str(i)] = Train['seek_help'].astype(str)+'_'+Train[i].astype(str)
    Test1['seek_help'+str(i)] = Test['seek_help'].astype(str)+'_'+Test[i].astype(str)

In [28]:
cols = ['leave',
        'mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['anonymity'+str(i)] = Train['anonymity'].astype(str)+'_'+Train[i].astype(str)
    Test1['anonymity'+str(i)] = Test['anonymity'].astype(str)+'_'+Test[i].astype(str)

In [29]:
cols = ['mental_health_consequence', 'phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['leave'+str(i)] = Train['leave'].astype(str)+'_'+Train[i].astype(str)
    Test1['leave'+str(i)] = Test['leave'].astype(str)+'_'+Test[i].astype(str)

In [30]:
cols = ['phys_health_consequence', 'coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['mental_health_consequence'+str(i)] = Train['mental_health_consequence'].astype(str)+'_'+Train[i].astype(str)
    Test1['mental_health_consequence'+str(i)] = Test['mental_health_consequence'].astype(str)+'_'+Test[i].astype(str)

In [31]:
cols = ['coworkers',
        'supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['phys_health_consequence'+str(i)] = Train['phys_health_consequence'].astype(str)+'_'+Train[i].astype(str)
    Test1['phys_health_consequence'+str(i)] = Test['phys_health_consequence'].astype(str)+'_'+Test[i].astype(str)

In [32]:
cols = ['supervisor', 'mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['coworkers'+str(i)] = Train['coworkers'].astype(str)+'_'+Train[i].astype(str)
    Test1['coworkers'+str(i)] = Test['coworkers'].astype(str)+'_'+Test[i].astype(str)

In [33]:
cols = ['mental_health_interview', 'phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['supervisor'+str(i)] = Train['supervisor'].astype(str)+'_'+Train[i].astype(str)
    Test1['supervisor'+str(i)] = Test['supervisor'].astype(str)+'_'+Test[i].astype(str)

In [34]:
cols = ['phys_health_interview',
        'mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['mental_health_interview'+str(i)] = Train['mental_health_interview'].astype(str)+'_'+Train[i].astype(str)
    Test1['mental_health_interview'+str(i)] = Test['mental_health_interview'].astype(str)+'_'+Test[i].astype(str)

In [35]:
cols = ['mental_vs_physical', 'obs_consequence']

for i in cols:
    Train1['phys_health_interview'+str(i)] = Train['phys_health_interview'].astype(str)+'_'+Train[i].astype(str)
    Test1['phys_health_interview'+str(i)] = Test['phys_health_interview'].astype(str)+'_'+Test[i].astype(str)

In [36]:
cols = ['obs_consequence']

for i in cols:
    Train1['mental_vs_physical'+str(i)] = Train['mental_vs_physical'].astype(str)+'_'+Train[i].astype(str)
    Test1['mental_vs_physical'+str(i)] = Test['mental_vs_physical'].astype(str)+'_'+Test[i].astype(str)

In [37]:
Train1 = pd.get_dummies(Train, columns = ['Gender', 'Country', 'state',
                                           'self_employed', 'family_history', 'work_interfere',
                                           'no_employees', 'remote_work', 'tech_company', 'benefits',
                                           'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
                                           'mental_health_consequence', 'phys_health_consequence', 'coworkers',
                                           'supervisor', 'mental_health_interview', 'phys_health_interview',
                                           'mental_vs_physical', 'obs_consequence'])

In [38]:
Test1 = pd.get_dummies(Train, columns = ['Gender', 'Country', 'state',
                                         'self_employed', 'family_history', 'work_interfere',
                                         'no_employees', 'remote_work', 'tech_company', 'benefits',
                                         'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
                                         'mental_health_consequence', 'phys_health_consequence', 'coworkers',
                                         'supervisor', 'mental_health_interview', 'phys_health_interview',
                                         'mental_vs_physical', 'obs_consequence'])

In [39]:
print('Training set before dummies', Train.shape)
print('Testing set before dummies', Test.shape)
print('Training set after dummies', Train1.shape)
print('Testing set after dummies', Test1.shape)

Training set before dummies (1048, 258)
Testing set before dummies (210, 257)
Training set after dummies (1048, 428)
Testing set after dummies (1048, 428)

In [40]:
columns = ['Gender', 'Country', 'state',
           'self_employed', 'family_history', 'work_interfere',
           'no_employees', 'remote_work', 'tech_company', 'benefits',
           'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
           'mental_health_consequence', 'phys_health_consequence', 'coworkers',
           'supervisor', 'mental_health_interview', 'phys_health_interview',
           'mental_vs_physical', 'obs_consequence']
Train1[columns] = Train[columns]
Test1[columns] = Test[columns]
Test2 = Test1.drop(['treatment'], axis = 1)

In [41]:
print('Training set shape', Train1.shape)
print('Testing set shape', Test2.shape)

Training set shape (1048, 451)
Testing set shape (1048, 450)

In [42]:
#Label Encoder

for i in Train1.columns:
    if (Train1[i].dtypes == 'object'):
        Train1[i] = label.fit_transform(Train1[i])
        
for i in Test2.columns:
    if (Test2[i].dtypes == 'object'):
        Test2[i] = label.fit_transform(Test2[i])

In [43]:
Train1.to_csv('new_train.csv', index = False)
Test2.to_csv('new_test.csv', index = False)

In [44]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import f1_score, accuracy_score

import warnings
warnings.filterwarnings('ignore')

In [45]:
train = pd.read_csv('new_train.csv')
test = pd.read_csv('new_test.csv')

# train test splitting of data

In [46]:
X = train.drop(['treatment'], axis = 1)
y = train[['treatment']]

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 500)

In [48]:
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

lin = LinearRegression()
log = LogisticRegression()
Rd = Ridge()
Ls = Lasso()
KNN = KNeighborsRegressor()
NB = GaussianNB() 
SVM = SVR()
DT = DecisionTreeRegressor(criterion='mse', splitter='best', 
                           max_depth=5000, min_samples_split=2, min_samples_leaf=1, 
                           min_weight_fraction_leaf=0.0, max_features=None, 
                           random_state=None, max_leaf_nodes=None, 
                           min_impurity_decrease=0, min_impurity_split=None, 
                           ccp_alpha=0)
RF = RandomForestRegressor(n_estimators=500, criterion='mse', max_depth=None, 
                             min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                             max_features='log2', max_leaf_nodes=None, min_impurity_decrease=0.0, 
                             min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=-1, 
                             random_state=None, verbose=0, warm_start=False, 
                             ccp_alpha=0.0, max_samples=None)

BR = BaggingRegressor(base_estimator = DT)
GBR = GradientBoostingRegressor()
xgboost=XGBRegressor()

In [49]:
log.fit(X_train, y_train)
y_pred = log.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred)
print('MSE:     ', MSE)
rmse1 = np.sqrt(MSE)
print('rmse is:    ',rmse1)
f1_score1 = f1_score(y_test, y_pred, average = 'weighted')
print("f1_score is:     ", f1_score1)
accuracy_score1 = accuracy_score(y_test, y_pred)
print("accuracy_score is:     ", accuracy_score1)

MSE:      0.45714285714285713
rmse is:     0.6761234037828132
f1_score is:      0.382010582010582
accuracy_score is:      0.5428571428571428

algo = [lin, log, Rd, Ls, KNN, NB, SVM, DT, RF, BR, GBR, xgboost]

In [50]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc = dtc.fit(X_train, y_train)
y_pred2 = dtc.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred2)
print('MSE:     ', MSE)
rmse2 = np.sqrt(MSE)
print('rmse is:    ',rmse2)
f1_score2 = f1_score(y_test, y_pred2, average = 'weighted')
print("f1_score is:     ", f1_score2)
accuracy_score2 = accuracy_score(y_test, y_pred2)
print("accuracy_score is:     ", accuracy_score2)

MSE:      0.319047619047619
rmse is:     0.5648430038936652
f1_score is:      0.6815100678758711
accuracy_score is:      0.680952380952381

In [51]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc = rfc.fit(X_train, y_train)
y_pred3 = rfc.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred3)
print('MSE:     ', MSE)
rmse3 = np.sqrt(MSE)
print('rmse is:    ',rmse3)
f1_score3 = f1_score(y_test, y_pred3, average = 'weighted')
print("f1_score is:     ", f1_score3)
accuracy_score3 = accuracy_score(y_test, y_pred3)
print("accuracy_score is:     ", accuracy_score3)

MSE:      0.2904761904761905
rmse is:     0.5389584311207967
f1_score is:      0.7083698440444031
accuracy_score is:      0.7095238095238096

In [52]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier()
abc = abc.fit(X_train, y_train)
y_pred4 = abc.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred4)
print('MSE:     ', MSE)
rmse4 = np.sqrt(MSE)
print('rmse is:    ',rmse4)
f1_score4 = f1_score(y_test, y_pred4, average = 'weighted')
print("f1_score is:     ", f1_score4)
accuracy_score4 = accuracy_score(y_test, y_pred4)
print("accuracy_score is:     ", accuracy_score4)

MSE:      0.2761904761904762
rmse is:     0.5255382728122436
f1_score is:      0.7238095238095237
accuracy_score is:      0.7238095238095238

In [53]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
gbc = gbc.fit(X_train, y_train)
y_pred5 = abc.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred5)
print('MSE:     ', MSE)
rmse5 = np.sqrt(MSE)
print('rmse is:    ',rmse5)
f1_score5 = f1_score(y_test, y_pred5, average = 'weighted')
print("f1_score is:     ", f1_score5)
accuracy_score5 = accuracy_score(y_test, y_pred5)
print("accuracy_score is:     ", accuracy_score5)

MSE:      0.2761904761904762
rmse is:     0.5255382728122436
f1_score is:      0.7238095238095237
accuracy_score is:      0.7238095238095238

In [54]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn = knn.fit(X_train, y_train)
y_pred6 = knn.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred6)
print('MSE:     ', MSE)
rmse6 = np.sqrt(MSE)
print('rmse is:    ',rmse6)
f1_score6 = f1_score(y_test, y_pred6, average = 'weighted')
print("f1_score is:     ", f1_score6)
accuracy_score6 = accuracy_score(y_test, y_pred6)
print("accuracy_score is:     ", accuracy_score6)

MSE:      0.4142857142857143
rmse is:     0.6436503043467892
f1_score is:      0.5864766188626339
accuracy_score is:      0.5857142857142857

In [55]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)
y_pred7 = gnb.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred7)
print('MSE:     ', MSE)
rmse7 = np.sqrt(MSE)
print('rmse is:    ',rmse7)
f1_score7 = f1_score(y_test, y_pred7, average = 'weighted')
print("f1_score is:     ", f1_score7)
accuracy_score7 = accuracy_score(y_test, y_pred7)
print("accuracy_score is:     ", accuracy_score7)

MSE:      0.45714285714285713
rmse is:     0.6761234037828132
f1_score is:      0.382010582010582
accuracy_score is:      0.5428571428571428

In [56]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb = xgb.fit(X_train, y_train)
y_pred8 = xgb.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred8)
print('MSE:     ', MSE)
rmse8 = np.sqrt(MSE)
print('rmse is:    ',rmse8)
f1_score8 = f1_score(y_test, y_pred8, average = 'weighted')
print("f1_score is:     ", f1_score8)
accuracy_score8 = accuracy_score(y_test, y_pred8)
print("accuracy_score is:     ", accuracy_score8)

[14:57:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
MSE:      0.3238095238095238
rmse is:     0.5690426379538917
f1_score is:      0.6755440911506605
accuracy_score is:      0.6761904761904762

In [57]:
from sklearn.svm import SVC
svc = SVC()
svc = svc.fit(X_train, y_train)
y_pred9 = svc.predict(X_test)
MSE = metrics.mean_squared_error(y_test,y_pred9)
print('MSE:     ', MSE)
rmse9 = np.sqrt(MSE)
print('rmse is:    ',rmse9)
f1_score9 = f1_score(y_test, y_pred9, average = 'weighted')
print("f1_score is:     ", f1_score9)
accuracy_score9 = accuracy_score(y_test, y_pred9)
print("accuracy_score is:     ", accuracy_score9)

MSE:      0.45714285714285713
rmse is:     0.6761234037828132
f1_score is:      0.382010582010582
accuracy_score is:      0.5428571428571428

In [58]:
Algo_names = ['log','Dt', 'RF', 'ADboost', 'Gradientboost', 'KNN', 'NB', 'SVM', 'xgboost']
f1_scores = [f1_score1,f1_score2,f1_score3,f1_score4,f1_score5,f1_score6,f1_score7,f1_score8,f1_score9]
rmse_list = [rmse1,rmse2,rmse3,rmse4,rmse5,rmse6,rmse7,rmse8,rmse9]
accuracy_scores = [accuracy_score1,accuracy_score2,accuracy_score3,accuracy_score4,accuracy_score5,
                  accuracy_score6,accuracy_score7,accuracy_score8,accuracy_score9]

In [59]:
evaluation = pd.DataFrame({'Model': Algo_names,'f1_score' : f1_scores,
                           'RMSE': rmse_list, 'accuracy_score' : accuracy_scores})
evaluation.sort_values(by = 'f1_score', ascending = False)

           Model  f1_score      RMSE  accuracy_score
3        ADboost  0.723810  0.525538        0.723810
4  Gradientboost  0.723810  0.525538        0.723810
2             RF  0.708370  0.538958        0.709524
1             Dt  0.681510  0.564843        0.680952
7            SVM  0.675544  0.569043        0.676190
5            KNN  0.586477  0.643650        0.585714
0            log  0.382011  0.676123        0.542857
6             NB  0.382011  0.676123        0.542857
8        xgboost  0.382011  0.676123        0.542857

In [60]:
submission = pd.read_csv('sample.csv')
model = rfc
model.fit(X_train, y_train)
pred = model.predict(test)
Pred1 = np.where(pred > 0.5, "Yes", "No")
submission['Predictions'] = Pred1[210]
submission.to_csv('ADBoost72%model.csv', index = False)

In [61]:
print('f1_score:{:.2f} %'. format(f1_score4.mean()*100))

f1_score:72.38 %